// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIjAlZ9kfUBr7eU1QKb5GN5Ek6z4WiipM',
    appId: '1:71797694404:web:071121770d4531eee6ce91',
    messagingSenderId: '71797694404',
    projectId: 'fir-be497',
    authDomain: 'fir-be497.firebaseapp.com',
    storageBucket: 'fir-be497.firebasestorage.app',
    measurementId: 'G-Z7L3TBQ25E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF8lPFLtjB8siRfkr-xNPU1uBKT2jNzUU',
    appId: '1:71797694404:android:9448012210c0cd45e6ce91',
    messagingSenderId: '71797694404',
    projectId: 'fir-be497',
    storageBucket: 'fir-be497.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5E1wuunm-8TphZK9YJsIO8xcBUT46dRw',
    appId: '1:71797694404:ios:64c6e20d10220c91e6ce91',
    messagingSenderId: '71797694404',
    projectId: 'fir-be497',
    storageBucket: 'fir-be497.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5E1wuunm-8TphZK9YJsIO8xcBUT46dRw',
    appId: '1:71797694404:ios:64c6e20d10220c91e6ce91',
    messagingSenderId: '71797694404',
    projectId: 'fir-be497',
    storageBucket: 'fir-be497.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIjAlZ9kfUBr7eU1QKb5GN5Ek6z4WiipM',
    appId: '1:71797694404:web:8d04bdf9f6e2f282e6ce91',
    messagingSenderId: '71797694404',
    projectId: 'fir-be497',
    authDomain: 'fir-be497.firebaseapp.com',
    storageBucket: 'fir-be497.firebasestorage.app',
    measurementId: 'G-E2HQ76T3VV',
  );
}
